routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

include 'messenger.php';
Route::get('download/{filename}', function($filename)
{
    // Check if file exists in app/storage/file folder
    $file_path = 'public/downloads/'. $filename;
    if (file_exists($file_path))
    {
        // Send Download
        return Response::download($file_path, $filename, [
            'Content-Length: '. filesize($file_path)
        ]);
    }
    else
    {
        // Error
        exit('Requested file does not exist on our server!');
    }
})->name('download');
Route::get('welcome/{locale}', function ($locale) {
    App::setLocale($locale);
    return view('welcome');
    //
});
Route::get('/test', function () {
    return view('test');
});

Route::get('/support', function () {
    return view('frontend.support');
});
Route::get('/editprofile', function () {
    return view('admin.users.editprofile');
});
Route::get('/', 'FrontEndController@index')->name('index1');
Route::get('/profile/{username}', 'FrontEndController@profile')->name('profile');

Route::get('/viewgig/{slug}', 'FrontEndController@viewgig')->name('viewgig');
Route::get('/opengig/{slug}','FrontEndController@details')->name('gigOpen');

Route::post('/ajaxSearch','SearchController@ajaxSearch')->name('searchAjax');
Route::get('/search','SearchController@index')->name('search');
Auth::routes();
Route::group(['prefix' => 'admin',  'middleware' => 'auth'], function()
{
Route::get('/order/history/{id}','OrderController@index')->name('history');
Route::get('/files/{name}','ChatFileController@file')->name('file');

Route::resource('services','ServiceController');
Route::get('/service/ajax','ServiceController@Serviceajax')->name('Serviceajax');
Route::get('/editprofile', 'UserController@updateuserProfile')->name('editprofile');

Route::resource('offers','OfferController');

Route::resource('orderitemfile','OrderItemFileController');

Route::get('/offer/ajax','OfferController@Offerajax')->name('Offerajax');
Route::get('/order/ajax','OfferController@offerz')->name('orderajax');
Route::get('/offers','OfferController@offer')->name('offers');

Route::resource('users','UserController');
Route::get('/user/ajax','UserController@Userajax')->name('Userajax');

Route::resource('categories','CategoryController');
Route::resource('ChatFile','ChatFileController');
Route::get('/category/ajax','CategoryController@Categoryajax')->name('Categoryajax');

Route::resource('subcategories','SubCategoryController');
Route::get('/subcategory/ajax','SubCategoryController@Subcategoryajax')->name('Subcategoryajax');

Route::resource('skills','SkillController');
Route::get('/skill/ajax','SkillController@Skillajax')->name('Skillajax');

Route::get('/user/profile/{id}','UserController@userprofile')->name('userProfile');
    Route::get('/home', 'FrontEndController@index')->name('ahome');


    Route::get('/chat', 'OfferController@chat')->name('chat');

    Route::post('/chatCreate', 'OfferController@chatCreate')->name('chatCreate');


    Route::get('orders/received','OfferController@index')->name('offersReceived');
    Route::get('offers/ajax','OfferController@ajaxOffers')->name('ajaxOffers');
    Route::post('/Approved','OfferController@accpet')->name('Approved');
    Route::post('/Reject','OfferController@reject')->name('Reject');
    Route::post('/DeliveryReject','OfferController@DeliveryReject')->name('DeliveryReject');
    Route::post('/Deliver','OfferController@Deliver')->name('Deliver');
    Route::get('/accepted','OfferController@accepted')->name('accepted');
    Route::get('/reviews','OfferController@review')->name('Review');

    Route::get('paywithpaypal', array('as' => 'checkout.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'checkout.payment','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'checkout.status','uses' => 'AddMoneyController@getPaymentStatus',));

    Route::get('/settings', 'SettingController@show')->name('settings.show');
    Route::post('/settings', 'SettingController@update')->name('settings.update');
    Route::get('/getsubcat','SubCategoryController@getsub')->name('getsubcat');
    Route::get('/subcities','CityController@getCity')->name('getsubcities');
//    Route::get('offers/received','OfferController@index');


});
Route::group(['prefix' => 'user',  'middleware' => 'auth'], function()
{
    Route::get('/editprofile', 'UserController@updateuserProfile')->name('editprofile');
    Route::get('/messages', 'UserController@messages')->name('messages');
    Route::resource('services','ServiceController');
    Route::get('/service/ajax','ServiceController@Serviceajax')->name('Serviceajax');
    Route::get('/order/history/{id}','OrderController@index')->name('history');

    Route::resource('users','UserController');
    Route::get('/user/ajax','UserController@Userajax')->name('Userajax');

    Route::resource('categories','CategoryController');
    Route::get('/category/ajax','CategoryController@Categoryajax')->name('Categoryajax');

    Route::resource('subcategories','SubCategoryController');
    Route::get('/subcategory/ajax','SubCategoryController@Subcategoryajax')->name('Subcategoryajax');

    Route::resource('skills','SkillController');
    Route::get('/skill/ajax','SkillController@Skillajax')->name('Skillajax');

    Route::get('/profile/{id}','UserController@userprofile')->name('Profile');

    Route::get('/home', 'FrontEndController@index')->name('uhome');
    Route::get('/chat', 'OfferController@chat')->name('chat');
    Route::post('/chatCreate', 'OfferController@chatCreate')->name('chatCreate');

    Route::get('orders/received','OfferController@index');
    Route::get('offers/ajax','OfferController@ajaxOffers')->name('ajaxOffers');
    Route::get('/order/ajax','OfferController@offerz')->name('orderajax');
    Route::get('/offers','OfferController@offer')->name('offers');
    Route::post('/Approved','OfferController@accpet')->name('Approved');
    Route::post('/reject','OfferController@reject')->name('Reject');

    Route::get('paywithpaypal', array('as' => 'checkout.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'checkout.payment','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'checkout.status','uses' => 'AddMoneyController@getPaymentStatus',));

    Route::get('/settings', 'SettingController@show')->name('settings.show');
    Route::post('/settings', 'SettingController@update')->name('settings.update');
    Route::get('orders/received','OfferController@index')->name('offersReceived');
    Route::get('/getsubcat','SubCategoryController@getsub')->name('getsubcat');
    Route::get('/accepted','OfferController@accepted')->name('accepted');
    Route::post('/DeliveryReject','OfferController@DeliveryReject')->name('DeliveryReject');
    Route::resource('ratings','RatingController');


});
Route::get('/gprofile/{id}','HomeController@gprofile')->name('GetProfile');

app/SubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
   protected $table='subcategories';
    public function service(){
        return $this->belongsTo('App\Service','subcategory_id');
    }
    public function category(){
        return $this->belongsTo('App\Category','category_id');
    }

}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\SubCategory;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.subcategories.index');
    }
    public function Subcategoryajax()
    {
        $subCategory = SubCategory::where('id', '>', 0)->with('category');

//        return $users;
        return Datatables::of($subCategory)
            ->addColumn('action', function (SubCategory $subCategory) {
                $btn = '<a href="' . route("subcategories.show", $subCategory->id) . '"><i class="fa fa-eye"></i></a>
	   	<a href="' . route("subcategories.edit", $subCategory->id) . '"><i class="fa fa-edit"></i></a>';
                return $btn . view('admin.subcategories.delete', compact('subCategory'))->render();
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::all();
        return  view('admin.subcategories.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            $request->validate([
            'name' => ['required', 'regex:/^[\pL\s\-]+$/u', 'string', 'max:255'],
            'category' => ['required'],
        ]);
        $subCategory = new SubCategory();
        $subCategory->name = $request->name;
        $subCategory->category_id = $request->category;
        $subCategory->save();
        return redirect(route('subcategories.index'))->with('msg', 'subCategory Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function show(SubCategory $subCategory)
    {
        return $subCategory;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(SubCategory $subCategory)
    {
        $categories=Category::all();
        return  view('admin.subcategories.edit',compact('subCategory','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SubCategory $subCategory)
    {
        $request->validate([
            'name' => ['required', 'regex:/^[\pL\s\-]+$/u', 'string', 'max:255'],
            'category' => ['required'],
        ]);
        $subCategory->name = $request->name;
        $subCategory->category_id = $request->category;
        $subCategory->save();
        return redirect(route('subcategories.index'))->with('msg', 'subCategory Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(SubCategory $subCategory)
    {
        $subCategory->delete();
        return redirect(route('subcategories.index'))->with('msg', 'subCategory Deleted Successfully');

    }
    public function getsub(Request $request){
        $subcategories=SubCategory::where('category_id',$request->id)->get();
         $html=view('admin.services.subcategories',compact('subcategories'))->render();
        return $html;
    }
}

resources/views/admin/subcategories/create.blade.php
@extends('layouts.master')

@section('content')

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Admin</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Services</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                <h4 class="page-title">Add New Service</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
{{--                    <h4 class="header-title">Bootstrap Validation - Normal</h4>--}}
{{--                    <p class="sub-header">Provide valuable, actionable feedback to your users with HTML5 form validation–available in all our supported browsers.</p>--}}

                    <form action="{{route('subcategories.store')}}" method="Post" class="needs-validation" novalidate>
                        @csrf
                        <div class="form-group mb-3">
                            <label for="validationCustom01">Sub Category Name</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Service Name" required>
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group mb-3">
                            <label>Category</label>
                            <select name="category" class="form-control @error('category') is-invalid @enderror">
                                <option value="" readonly>Category</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>

                            @error('category')
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <button class="btn btn-primary" type="submit">Submit form</button>
                    </form>

                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col-->


    </div>
    <!-- end row -->

@endsection

@section('script')

    <!-- Plugin js-->
    <script src="{{ URL::asset('public/ubold/assets/libs/parsleyjs/parsleyjs.min.js')}}"></script>

    <!-- Validation init js-->
    <script src="{{ URL::asset('public/ubold/assets/js/pages/form-validation.init.js')}}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/16.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>
@endsection

resources/views/admin/subcategories/delete.blade.php
<a href="#" onclick="frmdlt{{$subCategory->id}}.submit();"  title="Delete"><i class="fa fa-trash"></i> </a>
<form name="frmdlt{{$subCategory->id}}" action="{{ route('subcategories.destroy', $subCategory->id)}}" method="post">
    {!! method_field('delete') !!}
    {{csrf_field()}}
</form>

resources/views/admin/subcategories/edit.blade.php
@extends('layouts.master')

@section('content')

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Admin</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Services</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                <h4 class="page-title">Add New Service</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    {{--                    <h4 class="header-title">Bootstrap Validation - Normal</h4>--}}
                    {{--                    <p class="sub-header">Provide valuable, actionable feedback to your users with HTML5 form validation–available in all our supported browsers.</p>--}}

                    <form action="{{route('subcategories.update',$subCategory->id)}}" method="Post" class="needs-validation" novalidate>
                        @method('PUT')
                        @csrf
                        <div class="form-group mb-3">
                            <label for="validationCustom01">SubCategory Name</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name',$subCategory->name)}}" placeholder="Service Name" required>
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group mb-3">
                            <label>Category</label>
                            <select name="category" class="form-control @error('category') is-invalid @enderror">
                                <option value="" readonly>Category</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}" {{$subCategory->category_id == $category->id ? 'selected':''}}>{{$category->name}}</option>
                                    @endforeach
                            </select>

                            @error('category')
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <button class="btn btn-primary" type="submit">Submit form</button>
                    </form>

                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col-->


    </div>
    <!-- end row -->

@endsection

@section('script')

    <!-- Plugin js-->
    <script src="{{ URL::asset('public/ubold/assets/libs/parsleyjs/parsleyjs.min.js')}}"></script>

    <!-- Validation init js-->
    <script src="{{ URL::asset('public/ubold/assets/js/pages/form-validation.init.js')}}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/16.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>
@endsection

resources/views/admin/subcategories/index.blade.php
@extends('layouts.master')

@section('css')
    <!-- third party css -->
    <link href="{{ URL::asset('assets/libs/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
    <!-- third party css end -->
    <style>
        th.sorting {
            width: 100%!important;
        }
    </style>
@endsection

@section('content')

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Tables</a></li>
                        <li class="breadcrumb-item active">Datatables</li>
                    </ol>
                </div>
                <h4 class="page-title">Datatables</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Services</h4>
                    <p class="text-muted font-13 mb-4">
                    </p>

                    <table id="subcategory-datatable" class="table table-responsive table-bordered" style="width: 100%!important;">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>SubCategory Name</th>
                            <th>Category Name</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->
@endsection

@section('script')

    <!-- third party js -->
    <script src="{{ URL::asset('assets/libs/datatables/datatables.min.js')}}"></script>
    <script src="{{ URL::asset('assets/libs/pdfmake/pdfmake.min.js')}}"></script>
    <!-- third party js ends -->

    <!-- Datatables init -->
    <script src="{{ URL::asset('assets/js/pages/datatables.init.js')}}"></script>
    <script>
       $(document).ready(function () {


            $('#subcategory-datatable').DataTable({
                dom: 'Bfrtip',
                processing: true,
                serverSide: true,
                ajax: "{{ route('Subcategoryajax') }}",
                buttons: [
                    {{--{--}}
                        {{--    text: 'Add Hotel',--}}
                        {{--    action: '{{route('hotels.create')}}',--}}
                        {{--    className:'btn btn-primary'--}}
                        {{--    },--}}
                        'copy', 'excel', 'pdf'
                ],
                columns: [
                    {data: 'id', name: 'id',title:'id'},
                    {data: 'name', name: 'name',title:'Name'},
                    {data: 'category.name', name: 'category.name',title:'Name'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

        });
    </script>
@endsection

resources/views/admin/subcategories/show.blade.php
<?php