routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

include 'messenger.php';
Route::get('download/{filename}', function($filename)
{
    // Check if file exists in app/storage/file folder
    $file_path = 'public/downloads/'. $filename;
    if (file_exists($file_path))
    {
        // Send Download
        return Response::download($file_path, $filename, [
            'Content-Length: '. filesize($file_path)
        ]);
    }
    else
    {
        // Error
        exit('Requested file does not exist on our server!');
    }
})->name('download');
Route::get('welcome/{locale}', function ($locale) {
    App::setLocale($locale);
    return view('welcome');
    //
});
Route::get('/test', function () {
    return view('test');
});

Route::get('/support', function () {
    return view('frontend.support');
});
Route::get('/editprofile', function () {
    return view('admin.users.editprofile');
});
Route::get('/', 'FrontEndController@index')->name('index1');
Route::get('/profile/{username}', 'FrontEndController@profile')->name('profile');

Route::get('/viewgig/{slug}', 'FrontEndController@viewgig')->name('viewgig');
Route::get('/opengig/{slug}','FrontEndController@details')->name('gigOpen');

Route::post('/ajaxSearch','SearchController@ajaxSearch')->name('searchAjax');
Route::get('/search','SearchController@index')->name('search');
Auth::routes();
Route::group(['prefix' => 'admin',  'middleware' => 'auth'], function()
{
Route::get('/order/history/{id}','OrderController@index')->name('history');
Route::get('/files/{name}','ChatFileController@file')->name('file');

Route::resource('services','ServiceController');
Route::get('/service/ajax','ServiceController@Serviceajax')->name('Serviceajax');
Route::get('/editprofile', 'UserController@updateuserProfile')->name('editprofile');

Route::resource('offers','OfferController');

Route::resource('orderitemfile','OrderItemFileController');

Route::get('/offer/ajax','OfferController@Offerajax')->name('Offerajax');
Route::get('/order/ajax','OfferController@offerz')->name('orderajax');
Route::get('/offers','OfferController@offer')->name('offers');

Route::resource('users','UserController');
Route::get('/user/ajax','UserController@Userajax')->name('Userajax');

Route::resource('categories','CategoryController');
Route::resource('ChatFile','ChatFileController');
Route::get('/category/ajax','CategoryController@Categoryajax')->name('Categoryajax');

Route::resource('subcategories','SubCategoryController');
Route::get('/subcategory/ajax','SubCategoryController@Subcategoryajax')->name('Subcategoryajax');

Route::resource('skills','SkillController');
Route::get('/skill/ajax','SkillController@Skillajax')->name('Skillajax');

Route::get('/user/profile/{id}','UserController@userprofile')->name('userProfile');
    Route::get('/home', 'FrontEndController@index')->name('ahome');


    Route::get('/chat', 'OfferController@chat')->name('chat');

    Route::post('/chatCreate', 'OfferController@chatCreate')->name('chatCreate');


    Route::get('orders/received','OfferController@index')->name('offersReceived');
    Route::get('offers/ajax','OfferController@ajaxOffers')->name('ajaxOffers');
    Route::post('/Approved','OfferController@accpet')->name('Approved');
    Route::post('/Reject','OfferController@reject')->name('Reject');
    Route::post('/DeliveryReject','OfferController@DeliveryReject')->name('DeliveryReject');
    Route::post('/Deliver','OfferController@Deliver')->name('Deliver');
    Route::get('/accepted','OfferController@accepted')->name('accepted');
    Route::get('/reviews','OfferController@review')->name('Review');

    Route::get('paywithpaypal', array('as' => 'checkout.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'checkout.payment','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'checkout.status','uses' => 'AddMoneyController@getPaymentStatus',));

    Route::get('/settings', 'SettingController@show')->name('settings.show');
    Route::post('/settings', 'SettingController@update')->name('settings.update');
    Route::get('/getsubcat','SubCategoryController@getsub')->name('getsubcat');
    Route::get('/subcities','CityController@getCity')->name('getsubcities');
//    Route::get('offers/received','OfferController@index');


});
Route::group(['prefix' => 'user',  'middleware' => 'auth'], function()
{
    Route::get('/editprofile', 'UserController@updateuserProfile')->name('editprofile');
    Route::get('/messages', 'UserController@messages')->name('messages');
    Route::resource('services','ServiceController');
    Route::get('/service/ajax','ServiceController@Serviceajax')->name('Serviceajax');
    Route::get('/order/history/{id}','OrderController@index')->name('history');

    Route::resource('users','UserController');
    Route::get('/user/ajax','UserController@Userajax')->name('Userajax');

    Route::resource('categories','CategoryController');
    Route::get('/category/ajax','CategoryController@Categoryajax')->name('Categoryajax');

    Route::resource('subcategories','SubCategoryController');
    Route::get('/subcategory/ajax','SubCategoryController@Subcategoryajax')->name('Subcategoryajax');

    Route::resource('skills','SkillController');
    Route::get('/skill/ajax','SkillController@Skillajax')->name('Skillajax');

    Route::get('/profile/{id}','UserController@userprofile')->name('Profile');

    Route::get('/home', 'FrontEndController@index')->name('uhome');
    Route::get('/chat', 'OfferController@chat')->name('chat');
    Route::post('/chatCreate', 'OfferController@chatCreate')->name('chatCreate');

    Route::get('orders/received','OfferController@index');
    Route::get('offers/ajax','OfferController@ajaxOffers')->name('ajaxOffers');
    Route::get('/order/ajax','OfferController@offerz')->name('orderajax');
    Route::get('/offers','OfferController@offer')->name('offers');
    Route::post('/Approved','OfferController@accpet')->name('Approved');
    Route::post('/reject','OfferController@reject')->name('Reject');

    Route::get('paywithpaypal', array('as' => 'checkout.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'checkout.payment','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'checkout.status','uses' => 'AddMoneyController@getPaymentStatus',));

    Route::get('/settings', 'SettingController@show')->name('settings.show');
    Route::post('/settings', 'SettingController@update')->name('settings.update');
    Route::get('orders/received','OfferController@index')->name('offersReceived');
    Route::get('/getsubcat','SubCategoryController@getsub')->name('getsubcat');
    Route::get('/accepted','OfferController@accepted')->name('accepted');
    Route::post('/DeliveryReject','OfferController@DeliveryReject')->name('DeliveryReject');
    Route::resource('ratings','RatingController');


});
Route::get('/gprofile/{id}','HomeController@gprofile')->name('GetProfile');

app/Skill.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
    public function users(){
        return $this->belongsToMany('App\User');
    }
}

app/Http/Controllers/SkillController.php
<?php

namespace App\Http\Controllers;

use App\Skill;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Yajra\DataTables\DataTables;

class SkillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('admin.skills.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {

        return view('admin.skills.create');

    }

    public function Skillajax()
    {
        $skill = Skill::where('id', '>', 0);
//        return response()->json($service);
        return Datatables::of($skill)
            ->addColumn('action', function (Skill $skill) {
                $btn = '<a href="' . route("skills.show", $skill->id) . '"><i class="fa fa-eye"></i></a>
	   	<a href="' . route("skills.edit", $skill->id) . '"><i class="fa fa-edit"></i></a>';

                return $btn . view('admin.skills.delete', compact('skill'))->render();
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public
    function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'max:50', 'min:5']
        ]);
        $skill = new Skill();
        $skill->name = $request->name;
        $slug = SlugService::createSlug(Skill::class, 'slug', $request->name);
        $skill->save();
        return redirect(route('skills.index'))->with(['msg', 'Skill Created Successfully']);

    }

    /**
     * Display the specified resource.
     *
     * @param Skill $skill
     * @return Response
     */
    public
    function show(Skill $skill)
    {
      return $skill;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Skill $skill
     * @return Response
     */
    public
    function edit(Skill $skill)
    {
        return view('admin.skills.edit', compact('skill'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Skill $skill
     * @return Response
     */
    public
    function update(Request $request, Skill $skill)
    {
        $request->validate([
            'name' => ['required', 'max:50', 'min:5']
        ]);
        $skill->name = $request->name;
        $slug = SlugService::createSlug(Skill::class, 'slug', $request->name);
        $skill->save();
        return redirect(route('skills.index'))->with(['msg', 'Skill Updated Successfully']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Skill $skill
     * @return Response
     */
    public
    function destroy(Skill $skill)
    {
        $skill->delete();
        return redirect(route('skills.index'))->with(['msg', 'Skill Deleted Successfully']);

    }
}

resources/views/admin/skills/create.blade.php
@extends('layouts.master')

@section('content')

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Admin</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Services</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                <h4 class="page-title">Add New Service</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
{{--                    <h4 class="header-title">Bootstrap Validation - Normal</h4>--}}
{{--                    <p class="sub-header">Provide valuable, actionable feedback to your users with HTML5 form validation–available in all our supported browsers.</p>--}}

                    <form action="{{route('skills.store')}}" method="Post" class="needs-validation" novalidate>
                        @csrf
                        <div class="form-group mb-3">
                            <label for="validationCustom01">Skill Name</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Skill Name" required>
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <button class="btn btn-primary" type="submit">Submit form</button>
                    </form>

                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col-->


    </div>
    <!-- end row -->

@endsection

@section('script')

    <!-- Plugin js-->
    <script src="{{ URL::asset('public/ubold/assets/libs/parsleyjs/parsleyjs.min.js')}}"></script>

    <!-- Validation init js-->
    <script src="{{ URL::asset('public/ubold/assets/js/pages/form-validation.init.js')}}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/16.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>
@endsection

resources/views/admin/skills/delete.blade.php
<a href="#" onclick="frmdlt{{$skill->id}}.submit();"  title="Delete"><i class="fa fa-trash"></i> </a>
<form name="frmdlt{{$skill->id}}" action="{{ route('skills.destroy', $skill->id)}}" method="post">
    {!! method_field('delete') !!}
    {{csrf_field()}}
</form>

resources/views/admin/skills/edit.blade.php
@extends('layouts.master')

@section('content')

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Admin</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Services</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                <h4 class="page-title">Add New Service</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    {{--                    <h4 class="header-title">Bootstrap Validation - Normal</h4>--}}
                    {{--                    <p class="sub-header">Provide valuable, actionable feedback to your users with HTML5 form validation–available in all our supported browsers.</p>--}}

                    <form action="{{route('skills.update',$skill->id)}}" method="Post" class="needs-validation" novalidate>
                        @method('PUT')
                        @csrf
                        <div class="form-group mb-3">
                            <label for="validationCustom01">Skill Name</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name',$skill->name)}}" placeholder="Skill Name" required>
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <button class="btn btn-primary" type="submit">Submit form</button>
                    </form>

                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col-->


    </div>
    <!-- end row -->

@endsection

@section('script')

    <!-- Plugin js-->
    <script src="{{ URL::asset('public/ubold/assets/libs/parsleyjs/parsleyjs.min.js')}}"></script>

    <!-- Validation init js-->
    <script src="{{ URL::asset('public/ubold/assets/js/pages/form-validation.init.js')}}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/16.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>
@endsection

resources/views/admin/skills/index.blade.php
@extends('layouts.master')

@section('css')
    <!-- third party css -->
    <link href="{{ URL::asset('public/ubold/assets/libs/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
    <!-- third party css end -->
    <style>
        th.sorting {
            width: 100%!important;
        }
    </style>
@endsection

@section('content')

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Tables</a></li>
                        <li class="breadcrumb-item active">Datatables</li>
                    </ol>
                </div>
                <h4 class="page-title">Datatables</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Services</h4>
                    <p class="text-muted font-13 mb-4">
                    </p>

                    <table id="skill-datatable" class="table table-responsive table-bordered" style="width: 100%!important;">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->
@endsection

@section('script')

    <!-- third party js -->
    <script src="{{ URL::asset('public/ubold/assets/libs/datatables/datatables.min.js')}}"></script>
    <script src="{{ URL::asset('public/ubold/assets/libs/pdfmake/pdfmake.min.js')}}"></script>
    <!-- third party js ends -->

    <!-- Datatables init -->
    <script src="{{ URL::asset('public/ubold/assets/js/pages/datatables.init.js')}}"></script>
    <script>
       $(document).ready(function () {


            $('#skill-datatable').DataTable({
                dom: 'Bfrtip',
                processing: true,
                serverSide: true,
                ajax: "{{ route('Skillajax') }}",
                buttons: [
                    {{--{--}}
                        {{--    text: 'Add Hotel',--}}
                        {{--    action: '{{route('hotels.create')}}',--}}
                        {{--    className:'btn btn-primary'--}}
                        {{--    },--}}
                        'copy', 'excel', 'pdf'
                ],
                columns: [
                    {data: 'id', name: 'id',title:'id'},
                    {data: 'name', name: 'name',title:'Name'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

        });
    </script>
@endsection

resources/views/admin/skills/show.blade.php
<?php