routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

include 'messenger.php';
Route::get('download/{filename}', function($filename)
{
    // Check if file exists in app/storage/file folder
    $file_path = 'public/downloads/'. $filename;
    if (file_exists($file_path))
    {
        // Send Download
        return Response::download($file_path, $filename, [
            'Content-Length: '. filesize($file_path)
        ]);
    }
    else
    {
        // Error
        exit('Requested file does not exist on our server!');
    }
})->name('download');
Route::get('welcome/{locale}', function ($locale) {
    App::setLocale($locale);
    return view('welcome');
    //
});
Route::get('/test', function () {
    return view('test');
});

Route::get('/support', function () {
    return view('frontend.support');
});
Route::get('/editprofile', function () {
    return view('admin.users.editprofile');
});
Route::get('/', 'FrontEndController@index')->name('index1');
Route::get('/profile/{username}', 'FrontEndController@profile')->name('profile');

Route::get('/viewgig/{slug}', 'FrontEndController@viewgig')->name('viewgig');
Route::get('/opengig/{slug}','FrontEndController@details')->name('gigOpen');

Route::post('/ajaxSearch','SearchController@ajaxSearch')->name('searchAjax');
Route::get('/search','SearchController@index')->name('search');
Auth::routes();
Route::group(['prefix' => 'admin',  'middleware' => 'auth'], function()
{
Route::get('/order/history/{id}','OrderController@index')->name('history');
Route::get('/files/{name}','ChatFileController@file')->name('file');

Route::resource('services','ServiceController');
Route::get('/service/ajax','ServiceController@Serviceajax')->name('Serviceajax');
Route::get('/editprofile', 'UserController@updateuserProfile')->name('editprofile');

Route::resource('offers','OfferController');

Route::resource('orderitemfile','OrderItemFileController');

Route::get('/offer/ajax','OfferController@Offerajax')->name('Offerajax');
Route::get('/order/ajax','OfferController@offerz')->name('orderajax');
Route::get('/offers','OfferController@offer')->name('offers');

Route::resource('users','UserController');
Route::get('/user/ajax','UserController@Userajax')->name('Userajax');

Route::resource('categories','CategoryController');
Route::resource('ChatFile','ChatFileController');
Route::get('/category/ajax','CategoryController@Categoryajax')->name('Categoryajax');

Route::resource('subcategories','SubCategoryController');
Route::get('/subcategory/ajax','SubCategoryController@Subcategoryajax')->name('Subcategoryajax');

Route::resource('skills','SkillController');
Route::get('/skill/ajax','SkillController@Skillajax')->name('Skillajax');

Route::get('/user/profile/{id}','UserController@userprofile')->name('userProfile');
    Route::get('/home', 'FrontEndController@index')->name('ahome');


    Route::get('/chat', 'OfferController@chat')->name('chat');

    Route::post('/chatCreate', 'OfferController@chatCreate')->name('chatCreate');


    Route::get('orders/received','OfferController@index')->name('offersReceived');
    Route::get('offers/ajax','OfferController@ajaxOffers')->name('ajaxOffers');
    Route::post('/Approved','OfferController@accpet')->name('Approved');
    Route::post('/Reject','OfferController@reject')->name('Reject');
    Route::post('/DeliveryReject','OfferController@DeliveryReject')->name('DeliveryReject');
    Route::post('/Deliver','OfferController@Deliver')->name('Deliver');
    Route::get('/accepted','OfferController@accepted')->name('accepted');
    Route::get('/reviews','OfferController@review')->name('Review');

    Route::get('paywithpaypal', array('as' => 'checkout.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'checkout.payment','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'checkout.status','uses' => 'AddMoneyController@getPaymentStatus',));

    Route::get('/settings', 'SettingController@show')->name('settings.show');
    Route::post('/settings', 'SettingController@update')->name('settings.update');
    Route::get('/getsubcat','SubCategoryController@getsub')->name('getsubcat');
    Route::get('/subcities','CityController@getCity')->name('getsubcities');
//    Route::get('offers/received','OfferController@index');


});
Route::group(['prefix' => 'user',  'middleware' => 'auth'], function()
{
    Route::get('/editprofile', 'UserController@updateuserProfile')->name('editprofile');
    Route::get('/messages', 'UserController@messages')->name('messages');
    Route::resource('services','ServiceController');
    Route::get('/service/ajax','ServiceController@Serviceajax')->name('Serviceajax');
    Route::get('/order/history/{id}','OrderController@index')->name('history');

    Route::resource('users','UserController');
    Route::get('/user/ajax','UserController@Userajax')->name('Userajax');

    Route::resource('categories','CategoryController');
    Route::get('/category/ajax','CategoryController@Categoryajax')->name('Categoryajax');

    Route::resource('subcategories','SubCategoryController');
    Route::get('/subcategory/ajax','SubCategoryController@Subcategoryajax')->name('Subcategoryajax');

    Route::resource('skills','SkillController');
    Route::get('/skill/ajax','SkillController@Skillajax')->name('Skillajax');

    Route::get('/profile/{id}','UserController@userprofile')->name('Profile');

    Route::get('/home', 'FrontEndController@index')->name('uhome');
    Route::get('/chat', 'OfferController@chat')->name('chat');
    Route::post('/chatCreate', 'OfferController@chatCreate')->name('chatCreate');

    Route::get('orders/received','OfferController@index');
    Route::get('offers/ajax','OfferController@ajaxOffers')->name('ajaxOffers');
    Route::get('/order/ajax','OfferController@offerz')->name('orderajax');
    Route::get('/offers','OfferController@offer')->name('offers');
    Route::post('/Approved','OfferController@accpet')->name('Approved');
    Route::post('/reject','OfferController@reject')->name('Reject');

    Route::get('paywithpaypal', array('as' => 'checkout.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'checkout.payment','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'checkout.status','uses' => 'AddMoneyController@getPaymentStatus',));

    Route::get('/settings', 'SettingController@show')->name('settings.show');
    Route::post('/settings', 'SettingController@update')->name('settings.update');
    Route::get('orders/received','OfferController@index')->name('offersReceived');
    Route::get('/getsubcat','SubCategoryController@getsub')->name('getsubcat');
    Route::get('/accepted','OfferController@accepted')->name('accepted');
    Route::post('/DeliveryReject','OfferController@DeliveryReject')->name('DeliveryReject');
    Route::resource('ratings','RatingController');


});
Route::get('/gprofile/{id}','HomeController@gprofile')->name('GetProfile');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('public/js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer-script.blade.php
        <!-- Vendor js -->
        <script src="{{ URL::asset('public/ubold/assets/js/vendor.min.js')}}"></script>

        @yield('script')

        <!-- App js -->
        <script src="{{ URL::asset('public/ubold/assets/js/app.min.js')}}"></script>

        @yield('script-bottom')

resources/views/layouts/footer.blade.php
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                2015 - {{date('Y')}} &copy; UBold theme by <a href="">Coderthemes</a> 
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-sm-block">
                    <a href="javascript:void(0);">About Us</a>
                    <a href="javascript:void(0);">Help</a>
                    <a href="javascript:void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

resources/views/layouts/head.blade.php
        @yield('css')

        <!-- App css -->
        <link href="{{ URL::asset('public/ubold/assets/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{ URL::asset('public/ubold/assets/css/icons.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{ URL::asset('public/ubold/assets/css/app.min.css')}}" rel="stylesheet" type="text/css" />

resources/views/layouts/master-layouts.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>UBold - Responsive Admin Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="public/ubold/assets/images/favicon.ico">
        @include('layouts.head')

    </head>

    @yield('body')

        <!-- Navigation Bar-->
        <header id="topnav">
      @include('layouts.topbar')
      @include('layouts.nav-horizontal')
            </header>
        <!-- End Navigation Bar-->

        <!-- ============================================================== -->
        <!-- Start Page Content here -->
        <!-- ============================================================== -->
            <div class="wrapper">
                <div class="container-fluid">
      @yield('content')
      @include('layouts.right-sidebar')
    @include('layouts.footer')
                </div> <!-- content -->
            </div>
            <!-- END wrapper -->
    @include('layouts.footer-script')
    </body>
</html>

resources/views/layouts/master-without-nav.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>UBold - Responsive Admin Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="public/ubold/assets/images/favicon.ico">

        @include('layouts.head')
  </head>

@yield('body')

@yield('content')

@include('layouts.footer-script')
            </div>
        </div>
    </body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>UBold - Responsive Admin Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="public/ubold/assets/images/favicon.ico">
        @include('layouts.head')

    </head>

    <body>

        <!-- Navigation Bar-->
        <header id="topnav">
      @include('layouts.topbar')
      @include('layouts.nav-horizontal')
            </header>
        <!-- End Navigation Bar-->

        <!-- ============================================================== -->
        <!-- Start Page Content here -->
        <!-- ============================================================== -->
            <div class="wrapper">
                <div class="container-fluid">
    @yield('content')
    @include('layouts.footer')
    @include('layouts.right-sidebar')
            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->
                </div> <!-- end wrapper -->
            </div>
            <!-- end wrapper -->
    @include('layouts.footer-script')
    </body>
</html>

resources/views/layouts/nav-horizontal.blade.php
<div class="topbar-menu">
    <div class="container-fluid">
        <div id="navigation">
            <!-- Navigation Menu-->
            <ul class="navigation-menu">

                <li class="has-submenu">
                    <a href="#">
                        <i class="fe-airplay"></i>Services <div class="arrow-down"></div></a>
                    <ul class="submenu">
                        <li>
                            <a href="{{route('services.create')}}">Add New Service</a>
                        </li>
                        <li>
                            <a href="{{route('services.index')}}">View All Services</a>
                        </li>
                    </ul>
                </li>

                <li class="has-submenu">
                    <a href="#">
                        <i class="fe-grid"></i>Users <div class="arrow-down"></div></a>
                            <ul class="submenu">
                                <li>
                                    <a href="{{route('users.create')}}">Add New User</a>
                                </li>
                                <li>
                                    <a href="{{route('users.index')}}">View All Users</a>
                                </li>
                            </ul>
                </li>

                <li class="has-submenu">
                    <a href="{{route('offersReceived')}}"> <i class="fe-briefcase"></i>Offers Received <div class="arrow-down"></div></a>
{{--                    <ul class="submenu megamenu">--}}
{{--                        <li>--}}
{{--                            <ul>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-buttons">Buttons</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-cards">Cards</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-portlets">Portlets</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-tabs-accordions">Tabs & Accordions</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-modals">Modals</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-progress">Progress</a>--}}
{{--                                </li>--}}
{{--                            </ul>--}}
{{--                        </li>--}}
{{--                        <li>--}}
{{--                            <ul>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-notifications">Notifications</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-images">Images</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-carousel">Carousel</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-video">Embed Video</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-dropdowns">Dropdowns</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-spinners">Spinners</a>--}}
{{--                                </li>--}}
{{--                            </ul>--}}
{{--                        </li>--}}
{{--                        <li>--}}
{{--                            <ul>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-ribbons">Ribbons</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-tooltips-popovers">Tooltips & Popovers</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-general">General UI</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-typography">Typography</a>--}}
{{--                                </li>--}}
{{--                                <li>--}}
{{--                                    <a href="ui-grid">Grid</a>--}}
{{--                                </li>--}}
{{--                            </ul>--}}
{{--                        </li>--}}
{{--                    </ul>--}}
                </li>

                <li class="has-submenu">
                    <a href="#"> <i class="fe-cpu"></i>Categories <div class="arrow-down"></div></a>
                    <ul class="submenu">
                        <li>
                            <a href="{{route('categories.create')}}">Add New Category</a>
                        </li>
                        <li>
                            <a href="{{route('categories.index')}}">View All Categories</a>
                        </li>
                    </ul>
                </li>

                <li class="has-submenu">
                    <a href="#">
                        <i class="fe-layers"></i>Skills <div class="arrow-down"></div></a>
                    <ul class="submenu">
                                <li>
                                    <a href="{{route('skills.create')}}">Add New Skill</a>
                                </li>
                                <li>
                                    <a href="{{route('skills.index')}}">View All Skills</a>
                                </li>
                            </ul>
                        </li>
                <li class="has-submenu">
                            <a href="#">Sub Categories <div class="arrow-down"></div></a>
                            <ul class="submenu">
                                <li>
                                    <a href="{{route('subcategories.create')}}">Add New Sub Category</a>
                                </li>
                                <li>
                                    <a href="{{route('subcategories.index')}}">View All SubCategories</a>
                                </li>
                            </ul>
                        </li>

            </ul>
            <!-- End navigation menu -->

            <div class="clearfix"></div>
        </div>
        <!-- end #navigation -->
    </div>
    <!-- end container -->
</div>
<!-- end navbar-custom -->

resources/views/layouts/right-sidebar.blade.php
<!-- Right Sidebar -->
<div class="right-bar">
    <div class="rightbar-title">
        <a href="javascript:void(0);" class="right-bar-toggle float-right">
            <i class="dripicons-cross noti-icon"></i>
        </a>
        <h5 class="m-0 text-white">Settings</h5>
    </div>
    <div class="slimscroll-menu">
        <!-- User box -->
        <div class="user-box">
            <div class="user-img">
                <img src="assets/images/users/user-1.jpg" alt="user-img" title="Mat Helme" class="rounded-circle img-fluid">
                <a href="javascript:void(0);" class="user-edit"><i class="mdi mdi-pencil"></i></a>
            </div>
            
            <h5><a href="javascript: void(0);">Geneva Kennedy</a> </h5>
            <p class="text-muted mb-0"><small>Admin Head</small></p>
        </div>

        <!-- Settings -->
        <hr class="mt-0" />
        <h5 class="pl-3">Basic Settings</h5>
        <hr class="mb-0" />

        <div class="p-3">
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox1" type="checkbox" checked>
                <label for="Rcheckbox1">
                    Notifications
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox2" type="checkbox" checked>
                <label for="Rcheckbox2">
                    API Access
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox3" type="checkbox">
                <label for="Rcheckbox3">
                    Auto Updates
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox4" type="checkbox" checked>
                <label for="Rcheckbox4">
                    Online Status
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-0">
                <input id="Rcheckbox5" type="checkbox" checked>
                <label for="Rcheckbox5">
                    Auto Payout
                </label>
            </div>
        </div>

        <!-- Timeline -->
        <hr class="mt-0" />
        <h5 class="px-3">Messages <span class="float-right badge badge-pill badge-danger">25</span></h5>
        <hr class="mb-0" />
        <div class="p-3">
            <div class="inbox-widget">
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-2.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Tomaslau</a></p>
                    <p class="inbox-item-text">I've finished it! See you so...</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-3.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Stillnotdavid</a></p>
                    <p class="inbox-item-text">This theme is awesome!</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-4.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Kurafire</a></p>
                    <p class="inbox-item-text">Nice to meet you</p>
                </div>

                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-5.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Shahedk</a></p>
                    <p class="inbox-item-text">Hey! there I'm available...</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-6.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-dark">Adhamdannaway</a></p>
                    <p class="inbox-item-text">This theme is awesome!</p>
                </div>
            </div> <!-- end inbox-widget -->
        </div> <!-- end .p-3-->

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>